---

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install redis
  package:
    name: "{{ redis_package }}"
    state: present

- name: redis config file
  template:
    src: redisconf.j2
    dest: "{{ redis_conf }}"
    mode: 0644
  notify: restart redis

- name: redis service
  service:
    name: "{{ redis_servicename }}" 
    state: started 
    enabled: yes
  when: redis_manage_service
