---
dependency:
  name: galaxy
  enabled: true
driver:
  name: docker
platforms:
  - name: instance
    image: alpine:latest
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../
verifier:
  name: ansible
