---
dependency:
  name: galaxy
  enabled: true
driver:
  name: docker
platforms:
  - name: alpine
    image: alpine:latest
    privileged: true
  - name: centos8
    image: centos:8
    command: "/usr/sbin/init"
    privileged: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../
verifier:
  name: ansible
