---
dependency:
  name: galaxy
  enabled: true
driver:
  name: docker
platforms:
  - name: alpine
    image: alpine:latest
  - name: centos8
    image: centos:8
    command: "/usr/sbin/init"
  - name: ubuntu20
    image: ubuntu:20.04
    command: "/lib/systemd/systemd"
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../
verifier:
  name: ansible
